version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

