// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entities "github.com/johanVargas05/golang-api-hexagonal-architecture/src/domain/entities"
	mock "github.com/stretchr/testify/mock"

	pagination_dtos "github.com/johanVargas05/golang-api-hexagonal-architecture/src/domain/dtos/pagination"

	portfolio_dtos "github.com/johanVargas05/golang-api-hexagonal-architecture/src/domain/dtos/portfolio"
)

// AllPortFolioOfUserQueryUseCasePort is an autogenerated mock type for the AllPortFolioOfUserQueryUseCasePort type
type AllPortFolioOfUserQueryUseCasePort struct {
	mock.Mock
}

// Execute provides a mock function with given fields: params
func (_m *AllPortFolioOfUserQueryUseCasePort) Execute(params *portfolio_dtos.ParamsGetAllPortfolioOfUserDto) ([]*entities.Portfolio, *pagination_dtos.PaginationResponseDto, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.Portfolio
	var r1 *pagination_dtos.PaginationResponseDto
	var r2 error
	if rf, ok := ret.Get(0).(func(*portfolio_dtos.ParamsGetAllPortfolioOfUserDto) ([]*entities.Portfolio, *pagination_dtos.PaginationResponseDto, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*portfolio_dtos.ParamsGetAllPortfolioOfUserDto) []*entities.Portfolio); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Portfolio)
		}
	}

	if rf, ok := ret.Get(1).(func(*portfolio_dtos.ParamsGetAllPortfolioOfUserDto) *pagination_dtos.PaginationResponseDto); ok {
		r1 = rf(params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination_dtos.PaginationResponseDto)
		}
	}

	if rf, ok := ret.Get(2).(func(*portfolio_dtos.ParamsGetAllPortfolioOfUserDto) error); ok {
		r2 = rf(params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAllPortFolioOfUserQueryUseCasePort creates a new instance of AllPortFolioOfUserQueryUseCasePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAllPortFolioOfUserQueryUseCasePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *AllPortFolioOfUserQueryUseCasePort {
	mock := &AllPortFolioOfUserQueryUseCasePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
