// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entities "github.com/johanVargas05/golang-api-hexagonal-architecture/src/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// RunSeedRepositoryPort is an autogenerated mock type for the RunSeedRepositoryPort type
type RunSeedRepositoryPort struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RunSeedRepositoryPort) Execute(_a0 []*entities.Portfolio) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*entities.Portfolio) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRunSeedRepositoryPort creates a new instance of RunSeedRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunSeedRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunSeedRepositoryPort {
	mock := &RunSeedRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
