// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SeedRunCheckServicePort is an autogenerated mock type for the SeedRunCheckServicePort type
type SeedRunCheckServicePort struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *SeedRunCheckServicePort) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSeedRunCheckServicePort creates a new instance of SeedRunCheckServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSeedRunCheckServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SeedRunCheckServicePort {
	mock := &SeedRunCheckServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
